### PR TITLE
Fix GeneratorCacheWarmer with Symfony 7

### LINKED ISSUE #345: SF 7.x incompatibility with GeneratorCacheWarmer
Class: Admingenerator\GeneratorBundle\CacheWarmer\GeneratorCacheWarmer

Implements: Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface

Signature expects:

```php
    public function warmUp(string $cacheDir, ?string $buildDir = null): array;
```

Current implementation:

```php
    public function warmUp(string $cacheDir): array
```

Affects version 5.3.0, on clean install.

Solution: quick patch to class Admingenerator\GeneratorBundle\CacheWarmer\GeneratorCacheWarmer on branch 5.3.0

@bobvandevijver Agree?

### PR DESCRIPTION
**Pull request by tobias-93**
Fixes #345

### CODE REVIEW

File: CacheWarmer/GeneratorCacheWarmer.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ public function __construct(protected GeneratorCacheBuilder $generatorCacheBuild
     {
     }
 
-    public function warmUp(string $cacheDir): array
+    public function warmUp(string $cacheDir, string $buildDir = null): array
```
Comment (bobvandevijver) [inline CacheWarmer/GeneratorCacheWarmer.php:22]:
```suggestion
    public function warmUp(string $cacheDir, ?string $buildDir = null): array
```
